server:
  port: 0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:13001/ewm
    username: ewm_user
    password: secret
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
  output:
    ansi:
      enabled: always

stats-server:
  id: stats-server