server:
  port: 0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:13002/user
    username: user
    password: secret
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
  output:
    ansi:
      enabled: always
