syntax = "proto3";

package stats.service.dashboard;

import "google/protobuf/empty.proto";
import "stats/messages/request.proto";

option java_multiple_files = true;
option java_package = "ru.practicum.ewm.stats.proto";

service RecommendationsController {
  rpc GetRecommendationsForUser (stats.messages.request.UserPredictionsRequestProto)
      returns (stats.messages.request.RecommendedEventProto);

  rpc GetSimilarEvents (stats.messages.request.SimilarEventsRequestProto)
       returns (stats.messages.request.RecommendedEventProto);

  rpc GetInteractionsCount (stats.messages.request.InteractionsCountRequestProto)
         returns (stats.messages.request.RecommendedEventProto);
}