grpc:
  server:
    port: 0

analyzer:
  kafka:
    event-similarity-consumer-properties:
      bootstrap.servers: localhost:9092
      group.id: analyzer-snapshot
      key.deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value.deserializer: ru.practicum.kafka.deserializer.EventSimilarityDeserializer
    user-action-consumer-properties:
      bootstrap.servers: localhost:9092
      group.id: snapshot-processor
      key.deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value.deserializer: ru.practicum.kafka.deserializer.UserActionDeserializer
    topics:
      user-actions: stats.user-actions.v1
      events-similarity: stats.events-similarity.v1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:12999/analyzer
    username: analyzer_user
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always

logging:
  level:
    ru.practicum: INFO
    org.springframework.web: ERROR
    org.apache.kafka: ERROR
    org.apache.http: ERROR