server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery.locator.enabled: true
      default-filters:
        - name: Retry
          args:
            retries: 3
            series: SERVER_ERROR # Повторять при 5xx ошибках
            methods: GET, POST, PUT, DELETE
      routes:
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**, /users/*/events/**, /events/**, /admin/categories/**, /categories/**, /admin/compilations/**, /compilations/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**, /users/*/events/*/requests/**

        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=admin/comments/**, /users/*/comments/**, /comments/**