DROP TABLE IF EXISTS event_similarity CASCADE;
DROP TABLE IF EXISTS user_actions CASCADE;

CREATE TABLE IF NOT EXISTS event_similarity (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_event     BIGINT NOT NULL,
    second_event    BIGINT NOT NULL,
    score           DOUBLE PRECISION NOT NULL,
    timestamp       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    UNIQUE (first_event, second_event)
);

CREATE TABLE IF NOT EXISTS user_actions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    event_id            BIGINT NOT NULL,
    action_type         VARCHAR NOT NULL,
    timestamp           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    UNIQUE (user_id, event_id)
);